#ifndef KERNEL_VERSION_H
#define KERNEL_VERSION_H

#define KERNEL_VERSION_MAJOR 0
#define KERNEL_VERSION_MINOR 1
#define KERNEL_VERSION_PATCH 0

#define SHELL_VERSION_MAJOR 0
#define SHELL_VERSION_MINOR 2
#define SHELL_VERSION_PATCH 0

#endif // KERNEL_VERSION_H